### ISSUE TITLE
Exception thrown while executing MVVM's OnClosing

### ISSUE THREAD

**Issue by Alexx999** [MugenMvvmToolkit/MugenMvvmToolkit#15]
Call stack:

```
    MugenMvvmToolkit.WPF.dll!MugenMvvmToolkit.WPF.Infrastructure.AttachedValueProvider.ClearInternal(object item) Line 275  C#
    MugenMvvmToolkit.dll!MugenMvvmToolkit.Infrastructure.AttachedValueProviderBase.Clear(object item) Line 200  C#
    MugenMvvmToolkit.dll!MugenMvvmToolkit.ViewModels.ViewModelBase.DisposeInternal() Line 548   C#
    MugenMvvmToolkit.dll!MugenMvvmToolkit.ViewModels.ViewModelBase.Dispose() Line 448   C#
    MugenMvvmToolkit.dll!MugenMvvmToolkit.ViewModels.MultiViewModel.OnViewModelsChanged(System.Collections.IList newItems, System.Collections.IList oldItems, int oldStartingIndex) Line 249    C#
    MugenMvvmToolkit.dll!MugenMvvmToolkit.ViewModels.MultiViewModel.Clear() Line 153    C#
    Absio.CommonUI.Core.dll!Absio.CommonUI.Core.ViewModels.SettingsViewModel.OnClosing(object parameter) Line 74    C#
    MugenMvvmToolkit.dll!MugenMvvmToolkit.ViewModels.CloseableViewModel.CloseAsync(object parameter) Line 70    C#
    MugenMvvmToolkit.dll!MugenMvvmToolkit.ViewModels.ViewModelExtensions.TryCloseAsync(MugenMvvmToolkit.Interfaces.ViewModels.IViewModel viewModel, object parameter, MugenMvvmToolkit.Interfaces.Navigation.INavigationContext context, MugenMvvmToolkit.Models.NavigationType type) Line 264  C#
    MugenMvvmToolkit.dll!MugenMvvmToolkit.Infrastructure.Mediators.WindowViewMediatorBase<MugenMvvmToolkit.WPF.Interfaces.Views.IWindowView>.OnClosing(object parameter) Line 229   C#
    MugenMvvmToolkit.dll!MugenMvvmToolkit.Infrastructure.Mediators.WindowViewMediatorBase<MugenMvvmToolkit.WPF.Interfaces.Views.IWindowView>.CloseAsync(object parameter) Line 164  C#
    MugenMvvmToolkit.dll!MugenMvvmToolkit.Infrastructure.Mediators.WindowViewMediatorBase<MugenMvvmToolkit.WPF.Interfaces.Views.IWindowView>.OnViewClosing(object sender, System.ComponentModel.CancelEventArgs e) Line 259 C#
    MugenMvvmToolkit.WPF.dll!MugenMvvmToolkit.WPF.Infrastructure.Mediators.WindowViewMediator.OnClosing(object sender, System.ComponentModel.CancelEventArgs cancelEventArgs) Line 112  C#
```

Exception:

```
System.TypeInitializationException: The type initializer for 'MugenMvvmToolkit.Infrastructure.AttachedValueProviderDefault' threw an exception. ---> System.ArgumentException: 'AttachedValueDictionary' property was already registered by 'AttachedValueProviderBase'.
   at System.Windows.DependencyProperty.RegisterCommon(String name, Type propertyType, Type ownerType, PropertyMetadata defaultMetadata, ValidateValueCallback validateValueCallback)
   at System.Windows.DependencyProperty.RegisterAttached(String name, Type propertyType, Type ownerType, PropertyMetadata defaultMetadata)
   at MugenMvvmToolkit.Infrastructure.AttachedValueProviderDefault..cctor() in d:\src\OpenSource\github\MugenMvvmToolkit\Core\mugenmvvmtoolkit.core(pcl_winrt)\infrastructure\AttachedValueProvider.cs:line 203
   --- End of inner exception stack trace ---
   at MugenMvvmToolkit.Infrastructure.AttachedValueProviderDefault.GetOrAddAttachedValues(NotifyPropertyChangedBase model, Boolean addNew)
   at MugenMvvmToolkit.WPF.Infrastructure.AttachedValueProvider.GetOrAddAttachedDictionary(Object item, Boolean addNew) in d:\src\OpenSource\github\MugenMvvmToolkit\Core\MugenMvvmToolkit.Core(PCL_WinRT)\Infrastructure\AttachedValueProvider.cs:line 347
```

It is handled, however it looks somewhat weird

**Comment by vyacheslav-volkov** [comment]
Hi there,
It seems you are using a different assemblies, if you are using MugenMvvmToolkit.WPF(4.5) you should use the MugenMvvmToolkit(4.5 PCL_WinRT) instead of MugenMvvmToolkit(4.0).
